### ISSUE TITLE
The link for the Chi Square not working!

### ISSUE THREAD

**Issue by RoseKyalo** [learn-co-curriculum/dsc-chi-square#1]
## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [ ] Other (explain below)

### Source

```

```

## What OS Are You Using?

- [ ] OS X
- [ ] Windows
- [ ] WSL
- [ ] Linux
- [ ] Saturn Cloud from Canvas

**Comment by jessepisel** [comment]
thanks for opening this issue with the team @RoseKyalo :wave: Can you please provide some additional context on this issue? Is the Saturn Cloud link not working or is it one of links in the notebook itself?

**Comment by jessepisel** [comment]
without any additional information I am closing this issue at this time
